name: unit_tests
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
